package ar.edu.itba.paw.webapp.mapper.util;

import ar.edu.itba.paw.webapp.dto.ErrorDTO;

import javax.ws.rs.core.Response;
import java.net.URI;

public class ErrorResponseBuilder {
    private final ErrorDTO errorDTO = new ErrorDTO();

    private ErrorResponseBuilder() {}

    public static ErrorResponseBuilder builder() {
        return new ErrorResponseBuilder();
    }

    /**
     * Set the ErrorType associated to the URI that identifies the problem.
     */
    public ErrorResponseBuilder type(ErrorType type) {
        errorDTO.setType(type.getURI());
        return this;
    }

    /**
     * Set the HTTP status code generated by the origin server.
     */
    public ErrorResponseBuilder status(Response.Status status) {
        errorDTO.setStatus(status.getStatusCode());
        return this;
    }

    /**
     * Set a short, human-readable summary of the problem type.
     */
    public ErrorResponseBuilder title(String title) {
        errorDTO.setTitle(title);
        return this;
    }

    /**
     * Set a human-readable explanation specific to this occurrence of the problem. Should help the client correct the problem.
     */
    public ErrorResponseBuilder detail(String detail) {
        errorDTO.setDetail(detail);
        return this;
    }

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    public ErrorResponseBuilder instance(URI instance) {
        errorDTO.setInstance(instance);
        return this;
    }

    public Response build() {
        if (errorDTO.getType() == null || errorDTO.getTitle() == null || errorDTO.getStatus() == null) {
            throw new IllegalStateException("Missing parameters in error");
        }
        return Response.status(errorDTO.getStatus()).entity(errorDTO).build();
    }
}
